### ISSUE TITLE
Can't connect chrome client

### ISSUE THREAD

**Issue by susuaung** [kirill578/Android-Fine-Tuner#2]
Hi,
I can't connect to device in Fine Tuner Client. Please take a look at the attach image.

![finetunerclient](https://user-images.githubusercontent.com/34911968/34408235-fd308f68-ebf0-11e7-8971-2a8308ba5429.png)

**Comment by kirill578** [comment]
I uploaded a new version 0.3 that fixes this issue. should be live within a few hours

**Comment by kara46** [comment]
Yes. Chrome Client updated. But still can't connect. Takes too long and throws CONNECTION TIME OUT. 
I used emulator to test. Did I miss out something?

![cc time out](https://user-images.githubusercontent.com/34911968/34432686-1121c516-eca8-11e7-88d7-a0f5674aba53.png)
